name: table_view
description: TableView component for Angular
version: 0.1.2
environment:
  sdk: '>=1.24.2'

dependencies:
  angular: '^4.0.0'
  angular_components: '^0.6.0'

dev_dependencies:
  angular_test: '^1.0.0'
  test: '^0.12.24+6'
  browser: '^0.10.0+2'
  dart_to_js_script_rewriter: '^1.0.3'

transformers:
- angular:
      entry_points:
        - test/client/**_test.dart
        - example/**.dart
- test/pub_serve:
      $include: test/**_test{.*,}.dart
- $dart2js:
      commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter

web:
  compiler:
    debug: dartdevc